language: python
python:  
  - "3.7"
env:
  - DJANGO=2.2

install:
  - pip install Django==2.2
  - pip install pytz==2022.7.1
  - pip install python-dotenv==0.21.1
  - pip install asgiref==3.6.0
  - pip install sqlparse==0.4.3

script:
  - cd mysite

after_success:
