language: python
python:
  - "3.7"
env:
  - DJANGO=2.2

install:
  - pip install -r requirements.txt
  - pip install importlib-metadata
  - pip install black
  - pip install flake8
  - pip install coveralls

script:
  - cd mysite
  - black . --check
  - flake8 .
  - coverage run manage.py test --no-input

after_success: coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWSACCESSID
  secret_access_key: $AWSACCESSKEY
  region: "us-east-1"
  app: "swe-assignment"
  env: "swe-assignment-env"
  bucket_name: "elasticbeanstalk-us-east-1-006335820833"
  on:
    branch: main
